### ISSUE TITLE
Support lazy :ensure / package.el 

### ISSUE THREAD

**Issue by thomasf** [jwiegley/use-package#150]
Use case:  It can take over an hour to run init.el the first time when need a temporary emacs install somewhere.
  
 I haven't really thought about any implementation details at all, just wanted to get this down..  I realize that it might be a bit of a crazy thing to do.

**Comment by jwiegley** [comment]
Lazy ensure could make for some seriously latency when you tried to actually use that fast-booting Emacs though...  But I agree there should be a way to say "on demand only".

**Comment by jwiegley** [comment]
This is not something I want to work on, since I wouldn't be using it and thus it would be an under-tested feature as use-package continues to move forward.

I'm actually thinking about making new keywords "pluggable", so that others, like `req-package` can extend the functionality of `use-package` without requiring that these changes go into the base macro.
