### ISSUE TITLE
compilation error in macro argument

### ISSUE THREAD

**Issue by lurdan** [jwiegley/use-package#175]
With recent update, my compiled settings can't load correctly.

Though this code snippet can be loaded without compilation,
it says "Error (use-package): Symbol's value as variable is void: view-mode-exit"
when byte-compiled.
```
(use-package view
  :config
  (defmacro do-not-exit-view-mode-unless-writable-advice (f)
    `(defadvice ,f (around do-not-exit-view-mode-unless-writable activate)
       (if (and (buffer-file-name)
                (not (file-writable-p (buffer-file-name))))
           (message "File is unwritable, so stay in view-mode.")
         ad-do-it)))

  (do-not-exit-view-mode-unless-writable-advice view-mode-exit)
  (do-not-exit-view-mode-unless-writable-advice view-mode-disable)
  )
```
cf. http://www.emacswiki.org/emacs/ViewMode#toc6

It can workarounded as putting it outside of use-package declaration, but...

**Comment by jwiegley** [comment]
@lurdan Thank you for finding this example.  I've been working hard on byte-compiled behavior, and have found quite a few subtleties.

If you install the `macrostep`, you can put your cursor on the opening `(` of the `use-package` declaration, and invoke `macrostep-expand`, which will show you the expansion of the macro.  If you also set `byte-compile-current-file` to `t` for that buffer, you'll see what it expands to for the byte-compiler.

I'm wondering if this issue is being caused by the passing the `defmacro` as a quoted form to `eval-after-load`, where I'm wrapping the body in yet another macro.

But this example is simple enough that I try it here and get to the bottom of it.  Thanks again.

**Comment by jwiegley** [comment]
@lurdan This now works for me with the latest version.

Also, for the best results, your declaration should look like:

``` elisp
(use-package view
  :defines (view-mode-exit view-mode-disable)
  :preface
  (defmacro do-not-exit-view-mode-unless-writable-advice (f)
    `(defadvice ,f (around do-not-exit-view-mode-unless-writable activate)
       (if (and (buffer-file-name)
                (not (file-writable-p (buffer-file-name))))
           (message "File is unwritable, so stay in view-mode.")
         ad-do-it)))
  :config
  (do-not-exit-view-mode-unless-writable-advice view-mode-exit)
  (do-not-exit-view-mode-unless-writable-advice view-mode-disable))
```

**Comment by lurdan** [comment]
@jwiegley thanks quick fix!

But unfortunatelly, my setup doesn't work with latest use-package and suggested declaration.
I'm unsure which my other configuratios make some glitch, so I will try to sort out about it
and report back later.

**Comment by jwiegley** [comment]
@lurdan Please try again?  I removed a call to `macroexpand` which may have been hurting you.

**Comment by lurdan** [comment]
@jwiegley the latest version doesn't help.

I use config file as:
```
;;(setq debug-on-error t)
(byte-recompile-file "~/.emacs.d/config/80-view-mode.el" nil 0)
(load "~/.emacs.d/config/80-view-mode")
```
and get compiling message:
```
In end of data:
80-view-mode.el:15:1:Warning: the function
    `do-not-exit-view-mode-unless-writable-advice' is not known to be defined.
```
and use-package error message described at first.

**Comment by jwiegley** [comment]
@lurdan Please let me know if e8023b1 fixes your problem.

**Comment by lurdan** [comment]
@jwiegley Updating to latest, my problem has gone!

Thank you!
