### ISSUE TITLE
use-package :idle replacement

### ISSUE THREAD

**Issue by phillord** [jwiegley/use-package#179]
I wasn't clear with the notice about :idle whether this is a temporary thing or intended to be a full deprecation. I ask because I currently lazy load about 20 different packages.

Does the use of :defer, followed by :init achieve the same thing?

**Comment by thomasf** [comment]
see https://github.com/jwiegley/use-package#note-to-users-upgrading-to-20

**Comment by phillord** [comment]
Yeah, I read that. It looks like I can move by idle functions to init and call defer instead. But :idle used to use a list (and later a priority queue). Having 20 idle timers doesn't seem like a great idea to me.

Could the idle queue not be refactored to force :init instead? That would require fewer changes for me.

If :idle is coming back in some form, it would be useful to know -- I will wait for this rather than upgrading for the mo.

**Comment by npostavs** [comment]
> Yeah, I read that. It looks like I can move by idle functions to init and call defer instead.

`s/init/config` I think?

> But :idle used to use a list (and later a priority queue).

Yes, and it spaced out evaluations of each idle package. With the `:defer N` scheme, I would have to assign each package a time and space out the times manually.

**Comment by thomasf** [comment]
For me it worked well, it's still only executed on an idle timer.

**Comment by thomasf** [comment]
It's not a bad idea to let emacs idle timer schedule it for you either.  I guess the downside is that can't have too long timers if you are expecting to be typing for a while.. Mine are only at 1.5, 2 and 2.5 which works well.. usually if I stopped typing for 2.5 seconds emacs will have some time to do stuff for a second or two.

**Comment by jwiegley** [comment]
Do we know that having 20 idle timers is a bad idea?  Since elisp cannot process them asynchronously, it's effectively a queue.  I can't imagine that creating a timer object is that many more bytes than adding another cons cell to a list we manage ourselves.

The idea right now is that `:idle` is gone forever.  This is because I want to limit the number of "configuration" blocks exactly three keyword:

`:preface`, which happens before everything except `:disabled`, which means that in the expanded Lisp code it is never underneath an `if`, and thus fully visible to both `:if` and the byte-compiler.

`:init`, which happens immediately before `use-package` attempts to load the package.

`:config`, which happens after the package has loaded.

Thus, prior uses of `:idle` would now move to adding `:defer 5` and renaming `:idle` to `:config`.

There might have been cases where people were using `:idle` and expecting that the code would happen before the package was loaded -- because some of the time, this is exactly what would happen -- but such behavior is not guaranteed, which was the entire reason for removing `:idle` in the first place.  The only thing we can count on the idle timer for is to attempt to load the package if it has not already been, which will in turn cause the `:config` block to execute.

**Comment by thomasf** [comment]
I just added org and helm to `:defer 5` which I did not have on `:idle` before  because these recent changes made me notice which packages I had `:idle` before :+1:

**Comment by phillord** [comment]
Difficult to say whether 20 timers is a problem.I don't know enough about how emacs timers are scheduled to know whether they WILL form a queue or not -- I would be worried if the ordering is stochastic rather than worried about the overhead (which I wouldn't be worried about at all).

Can I suggest you update the documentation -- "I am removing this feature FOR NOW" seems to be wrong? In the meantime, if :idle is going to die, I will port my .emacs and report back. I guess I am one of the more extreme users of :idle (I have too many minor modes!)

**Comment by thomasf** [comment]
the amount of timers will not be a problem, emacs can handle at least thousands of those.
