### ISSUE TITLE
Use delight instead of diminish?

### ISSUE THREAD

**Issue by darkfeline** [jwiegley/use-package#187]
Advantages of using delight instead:

- Works on major modes too
- Properly handles mode line forms, like `(:eval (format " Minor Mode %s" variable))`
- Newer, for what it's worth.

EmacsWiki link: http://www.emacswiki.org/emacs/DelightedModes

**Comment by jwiegley** [comment]
So, right now I'm working on a scheme that will make use-package completely extensible by other users, so that packages like `req-package` will be able to plug directly into `use-package`.  It will make adding a new keyword like `:delight` trivial to do.

**Comment by jwiegley** [comment]
So here's what I recommend: develop `delight` separately as an addon for `use-package`, and it if works well for you we can include it later in `use-package` itself.

**Comment by syl20bnr** [comment]
> So, right now I'm working on a scheme that will make use-package completely extensible by other users

That's great ! I already see two useful keyword for spacemacs. Vive use-package !

**Comment by syl20bnr** [comment]
See https://github.com/syl20bnr/spacemacs/issues/903 for more info.

**Comment by darkfeline** [comment]
@jwiegley Do you support having third party addons using the new framework getting included into `use-package` itself or keeping them as separate addons for the discretion of the user to install?

**Comment by jwiegley** [comment]
@darkfeline Either way.  If it seems like a relatively small (i.e., not difficult to maintain) addon that will be of general use, like `:delight`, then I'm happy to include it into `use-package` itself.  Otherwise, if it's something a bit more involved that should have its own documentation, issue tracking, etc., (like `req-package`), then it should be a separate addon that users install themselves.

**Comment by jwiegley** [comment]
@syl20bnr Nice idea!
