### ISSUE TITLE
:face keyword

### ISSUE THREAD

**Issue by phillord** [jwiegley/use-package#221]
Sometimes when using a package I need to reset faces to something a bit nicer. It would be nice to have a handler rather like ":bind" which sets attributes of faces defined in the package (i.e. after the package has loaded). 

At the moment, I can handle this with "set-face-attributes" in :config but that's fairly ugly.

**Comment by jwiegley** [comment]
A balance must be struck between keeping `use-package` simple, and accommodating the most often occurring configuration patterns.  I'm not sure that configuring face attributes outside of `M-x customize-face` is worth having custom functionality in `use-package` at this point, since there is always `:config` or `customize`, as you point out.

That said, adding custom keywords like `:face` is now relatively trivial, and may be added to your own `init.el` file as a customization of `use-package` itself, before loading your package declarations.

**Comment by phillord** [comment]
No worries, just a thought. I currently customize faces in 2 places (adoc-mode and for smartparens), to a total of 6 faces, compared to 11 places where I use :bind, so I had my doubts about the genericity of it also.

I saw the new custom keyword support -- looked interesting, but not somewhere I'd like to go, since it introduces a cross-dependency between very distant parts of my .emacs file -- kind of what I use use-package to avoid!

Thanks anyway.
