### ISSUE TITLE
wise way of adopting use-package for existing .emacs?

### ISSUE THREAD

**Issue by biocyberman** [jwiegley/use-package#229]
I am still new to emacs, but I already use more than 20 packages and have a dozen of customized functions in my `.emacs` file. With many comments and careful editing, I still fear the mess would come someday. That lead me to `use-package`. However I am not clear how to make the transition. 

Following are about first 70 lines of my `.emacs` before and after the switching to `use-package`.  I cleaned up some redundant parts to look the excerpt more readable. Could you comment if I am doing it the right way. This can be use as a wiki article for future beginners. 

```elisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(package-archives
   (quote
    (("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa" . "http://stable.melpa.org/packages/"))))
 '(purpose-user-regexp-purposes (quote (("^.*-mode$" . coding) ("PM-[:alpha:]" . coding)))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

; Set path recursively to one folder
(let ((default-directory "~/.emacs.d/elpa/"))(normal-top-level-add-subdirs-to-load-path))

;; SOME POSSIBLE GLOBAL VARIABLES
(require 'undo-tree)
(global-undo-tree-mode)
(require 'helm)
(require 'helm-config)

(global-set-key (kbd "C-c h") 'helm-command-prefix)
(global-unset-key (kbd "C-x c"))

(helm-autoresize-mode t)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-x b") 'helm-mini)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(setq helm-semantic-fuzzy-match t
      helm-imenu-fuzzy-match    t)
(helm-mode 1)

;; enable open recent files
(require 'recentf)
(recentf-mode 1)
(global-set-key "\C-x\C-r" 'recentf-open-files)
```
After `use-package` integration

```elisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(package-archives
   (quote
    (("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa" . "http://stable.melpa.org/packages/"))))

 '(purpose-user-regexp-purposes (quote (("^.*-mode$" . coding) ("PM-[:alpha:]" . coding)))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

; Set path recursively to one folder
(let ((default-directory "~/.emacs.d/elpa/"))(normal-top-level-add-subdirs-to-load-path))
(package-initialize)
;; SOME POSSIBLE GLOBAL VARIABLES
;; Can't put many things to this sections because packages may need to be loaded first
;; Enable package management with use-package
(require 'use-package)
(use-package helm)
(use-package helm-config)

(global-set-key (kbd "C-c h") 'helm-command-prefix)
(global-unset-key (kbd "C-x c"))

(helm-autoresize-mode t)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-x b") 'helm-mini)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(setq helm-semantic-fuzzy-match t
      helm-imenu-fuzzy-match    t)
(helm-mode 1)

;; Reverse delete other windows
(use-package zygospore)
(global-set-key (kbd "C-x 1") 'zygospore-toggle-delete-other-windows)

;; enable open recent files
(use-package recentf)
(recentf-mode 1)
(global-set-key "\C-x\C-r" 'recentf-open-files)
```

**Comment by jwiegley** [comment]
Here's the guiding principle I use with `use-package`: What you would want to happen if the `use-package` declaration were disabled?  It should (1) disable the use of that feature completely, and (2) not in any way impact the usability of the other declarations.

This way, every piece of functionality in my environment is separately configured and controlled by a `use-package` declaration (aside from the variables defined with `customize-option`, since it's harmless to customize something that never loads).  It sometimes takes some thought to design things such that package A and B will each keep working if the other is disabled -- unless there is a direct dependency -- but I like being able to play with new features by bringing them in temporarily with a `use-package`.

**Comment by jwiegley** [comment]
I even create declarations for standard features of Emacs, if I'm adding *functionality* (i.e., not just configuration).  For example:

``` elisp
(use-package grep
  :bind (("M-s d" . find-grep-dired)
         ("M-s F" . find-grep)
         ("M-s G" . grep))
  :config
  (add-hook 'grep-mode-hook #'(lambda () (use-package grep-ed)))

  (grep-apply-setting 'grep-command "egrep -nH -e ")
  (grep-apply-setting
   'grep-find-command
   '("find . -type f -print0 | xargs -P4 -0 egrep -nH " . 49)))
```

**Comment by nickalcock** [comment]
I am tempted to extend use-package to support loading configuration options and other state from separate files, to assist translation from el-get, because I find splitting out the more complex modes into their own files more pleasant, and because I prefer to have configuration state at the top level rather than nested down inside parens and under a keyword argument.

This would let you say simply
(use-package foo)

then foo-init.el is 'required: if it exists, it's loaded *before* loading the package, with a binding in place that translates
(use-package-options ...)
into keyword options for the actual use-package call (which are overridden by real keyword arguments): (use-package-load) actually does the load, then the rest of the -init file gets evaluated to do the initialization. This is, as it were, 'use-package turned inside out'.

If you prefer 'lots of little files' this approach might help. I don't know, I'm still in the middle of hacking it up :) it looks like I can do the whole thing via advice, which means it might not need any actual changes to use-package at all...

**Comment by biocyberman** [comment]
Have been enjoying `use-package` very much so far, especially `:ensure` to download missing package, so I can have more potability and ease of swapping `.emacs.d` if I want. I've transformed almost all `(require 'primary-package)` to 
```elisp
(use-package primary-package 
:ensure t 
:init
(progn 
    (require 'secondary-pack)
    (some-command )
)
:bind
(some-key-bindings)
)
```

This all works fine execpt for this case, I don't know how to make it work yet: 

How do put this inside `(use-package ...)`:

```elisp
    (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action) ; rebind tab to run persistent action
    (define-key helm-map (kbd "C-i") 'helm-execute-persistent-action) ; make TAB works in terminal
 ```
That is, to use local mapping in this case `helm-map` instead of this binding style, which leads to global binding: 

```elisp
...
:bind(
         ("C-x C-b" . helm-buffers-list)
)
```

**Comment by nickalcock** [comment]
With a recent use-package (August), if the map you want is autoloaded and thus visibly a map when :bind runs (before the package is require'd and :config runs), you can say:

  :bind (:map vc-prefix-map
              ("B" . mo-git-blame-file)
              ("C" . mo-git-blame-current))

You *can* do this for maps that aren't autoloaded, by defining them in :init, but it's more or less not worth it: for such packages, I just do a (bind-keys :map ...) directly in :config. (It's not like a key on a non-autoloaded minor mode map can possibly trigger package loading, so you're not losing anything by doing it that way.)
