### ISSUE TITLE
influence handler that runs previously (:ensure)

### ISSUE THREAD

**Issue by steckerhalter** [jwiegley/use-package#239]
Hi!

Does anyone who knows `use-package` a bit better than me have an idea if `:ensure` can be set to nil for a handler that is after that in the keyword order?

See issue https://github.com/quelpa/quelpa-use-package/issues/1 for the details.

The only way I could think of was an advice but I felt guilty about it and thought "Hey, let's ask the guys over there..."

Thank you in advance!

**Comment by nickalcock** [comment]
If you arrange for your handler to do everything that influences :ensure at macro-expansion time *before* it calls 'use-package-process-keywords', and do everything that expands into text after that, then everything should work...

... *except* for turning off keywords entirely. Keywords can't do that, as far as I can see: each keyword can affect the behaviour of other keywords but cannot turn them off. The problem is that you're as likely as not to get your handler called from deep inside a call stack with the handler of the very keyword you're trying to turn off in it, since each handler calls 'use-package-process-keywords' to expand remaining handlers before doing it itself.

You can't even advise the ensure handler for this -- the place you'd have to change is *inside* it, not wrapping it. And you can't easily do it by modifying use-package-process-keywords unless you made it return a list or multiple values or something: it's already returning the macro-expansion body, after all. I think this might be a job for the normalizer -- i.e. have the thing you want to disable check the state for something injected by the normalizer for the keyword that disables it.

**Comment by steckerhalter** [comment]
Thanks for answering. The advice I wrote for the :ensure handler seems to work: https://github.com/quelpa/quelpa-use-package/blob/master/quelpa-use-package.el#L78

But I would of course prefer to do it like you are suggesting. Do you mean I could set :ensure to nil at macro-expansion time? That's what I need to do because if `use-package-always-ensure` is `t` it will fail if the package is not in any ELPA repo (which then quelpa should deal with).
