### ISSUE TITLE
don't fail on using internal packages with use-package-always-ensure

### ISSUE THREAD

**Issue by waymondo** [jwiegley/use-package#243]
I was excited to see the note about `(setq use-package-always-ensure t)` to globally ensure all packages and remove the repetitive `:ensure t` from my `init.el`, but this creates an issue when using `use-package` for internal packages. I like to wrap all customized packages with `use-package` but with the option set, it fails when evaluating a block like:

```
(use-package cus-edit
  :init (setq custom-file (locate-user-emacs-file "custom.el"))
  :config (load custom-file 'no-error 'no-message))
```

Is there a way to have the `:ensure` keyword also detect existing internal packages?

related to #233

**Comment by thomasf** [comment]
I guess that you should add `:ensure nil` to those packages (if that works)..
Just because a package is available inside of Emacs does not automatically mean that you don't want a newer version to be installed in place of it.

**Comment by jwiegley** [comment]
Yes, that should work.

**Comment by waymondo** [comment]
True, this works, but that would kind of defeat the purpose for me to use `use-package-always-ensure` since half of my `use-package` declarations are internal and half are pulled from a package archive.

Would it make sense to add a separate custom variable, called something like `use-package-always-ensure-if-not-available`, where if it was set and a package isn't found then it would call the `:ensure` keyword handling?

**Comment by thomasf** [comment]
That kind of lends itself to unexpected situations if package availability changes.

Personally I've always argued against the `always-ensure...` stuff because `:ensure t` is a really short snippet of code.  In my ~9.8kloc `init.el` I have 519 `use-package` instances and 391 uses of `:ensure ` which literally is next to nothing compared to what it brings in predictability.

**Comment by waymondo** [comment]
> That kind of lends itself to unexpected situations if package availability changes.

Can you explain an example like this? I'm not doubting you, I'm just curious and nothing is immediately popping into my head.

**Comment by thomasf** [comment]
Again, this is my personal opinion, others see i differently.

I'm not saying the problem happens alot but when/if packages that at one time was both in emacs and some package archive is removed from the archive I rather get a hard error instead of it going unnoticed when doing a fresh emacs install somewhere and possibly causing the need to debug my config. 

Most of the use-package keywords behaves very declarative with one default for all instances which imho is something that makes it a joy to use.
