### ISSUE TITLE
Question regarding best practices

### ISSUE THREAD

**Issue by sondr3** [jwiegley/use-package#344]
This is mostly a question out of pure curiosity, I was reading the Spacemacs coding conventions and saw that they required all `:init` and `:config` blocks spanning multiple lines to be wrapped in `progn` and asked on Gitter, but it didn't completely sate my curiosity. I've never used it in my `:config` or `:init` blocks myself and haven't had any problems with it. I was simply wondering if it's needed/why not?

I'm a bit of a Emacs newbie so sorry for the silly questions :smile:

**Comment by Silex** [comment]
The `progn` blocks are not *needed*, but some lispers think it makes it more clear what happens.

It's really personal taste.

**Comment by thomasf** [comment]
A single form (like wrapping in a progn) was required in use-package earlier ago so the spacemacs docs might be outdated. 

I like (progn ... ) because its the most common elisp way of simple code grouping 
and various packages like smartparens, expand-region, etc... are easier to work with when the parens are there.
