### ISSUE TITLE
Add "Documentation" String to use-package form

### ISSUE THREAD

**Issue by priyadarshan** [jwiegley/use-package#371]
It would be very nice to have `use-package` adopt a Documentation string, like elisp's defmacro does, e.g.:

```
(defmacro macro-example ()
  "Documentation string here")
```

```
(use-package recentf
  "Documentation string here"
  :init
   ;; etc) 
```

**Comment by npostavs** [comment]
Where would the string show up?  In other words, how is it different from a comment?

**Comment by priyadarshan** [comment]
`;` comments do not shows up in Emacs documentation.

A proper documentation string would show up in Emacs internal Doc strings, same as `describe-*` commands.

It seems that there is no such thing as `describe-macro`, though, as there is a `describe-function`.

**Comment by npostavs** [comment]
> It seems there is no such thing as `describe-macro`, though, equivalent to `describe-function`.

`describe-function` works on macros too, e.g. `(describe-function 'use-package)`, but there is no `describe-used-package` (or maybe `describe-use-package-configuration`?) function.

**Comment by priyadarshan** [comment]
Sorry, that is what I meant.

Some of my `use-package` instances have grown to be quite complex, I think I am not the only one there, and it would be neat to be able to have a proper Documentation string going with it, similarly to what one can do with regular defuns.

It would perhaps not make much sense in other packages (ie, offering a complex macro), but it would make the process more tidy. When I started using `use-package`, I got the feeling being "well, tidy" was part of its coding and usage ideal.

**Comment by raxod502** [comment]
Docstrings only make sense for objects that are defined in some way. For example, functions, variables, and macros are defined, and so one can attach docstrings to them. That is how `describe-function` and `describe-variable` operate, viz. by looking at the function or variable object and checking what its docstring is.

Docstrings don't make sense in the context of `use-package` because no object is being defined. Essentially, `use-package` is just `with-eval-after-load` with a lot of additional features to help simplify common tasks. It would be possible to hack on a docstring-like system, but I think it really makes more sense to just use a comment, as `use-package` forms can be more accurately described as code fragments rather than definitions.

**Comment by priyadarshan** [comment]
As an elisp absolute beginner, I see `use-package` as a pretty complex macro, and its instances are to me macro calls. Since they can be quite complex, I wish to be able to include proper documentation, as one can do for other semantic objects.

As I said earlier, I felt the words `"well, tidy"` in first paragraph of readme would be lenient to include handling documentation.

Of course I understand if the developers do not wish to add that feature. In that case, please feel free to close this ticket.

**Comment by raxod502** [comment]
I see your point. The way Elisp generally works is that you can put a docstring on a function definition but not a function call (similarly, a macro definition but not a macro call).

I think it would be perfectly reasonable to add some functionality in this area—I just wanted to explain why it wasn't there to begin with. But I'm not a `use-package` maintainer, so that's all I'll say.

**Comment by jwiegley** [comment]
I think just regular comments can be used, and docstrings are not necessary.

**Comment by raxod502** [comment]
@priyadarshan Something I noticed recently is that there is a `use-package-jump-to-package-form` function. So if you put a comment above your `use-package` form explaining its purpose, then `use-package-jump-to-package-form` is essentially `describe-function` for `use-package`.

**Comment by priyadarshan** [comment]
Thank you for pointing that out. I will try to use it, and, in case, I can work around it.

I was a bit sad to see this ticket rejected, let's say from the lisp aesthetics point of view, especially now that `use-package` is landing into core. For such an important part of many users, I felt my use-case was not uncommon. 

Thank you.

**Comment by jwiegley** [comment]
@priyadarshan A use-package declaration does not define anything, it is code that gets executed only (because it's a macro expansion).  So, associating a docstring with it doesn't actually make sense, since there isn't a value (or symbol) anywhere for that docstring to get associated with.

Note that you can always add your own support for a`:doc` keyword, via the keyword extension mechanism.

**Comment by priyadarshan** [comment]
Thank you for explaining and pointing to possible `:doc` keyword.

That seems the tidiest way, in the spirit of `use-package`. 

Thanks.
