### ISSUE TITLE
:diminish not working on any modes that are used globally

### ISSUE THREAD

**Issue by giodamelio** [jwiegley/use-package#381]
I am trying to use the `:diminish` keyword to hide some stuff from the modeline. It mostly works fine, but it won't hide any minor mode I enable globally. If if call diminish manually with M-x it works fine(<kbd>M-x</kbd> `diminish git-gutter-mode`). Here is an example of my `git-gutter-fringe` file.

``` emacs-lisp
(use-package git-gutter-fringe
  :ensure git-gutter
  :ensure fringe-helper
  :ensure git-gutter-fringe
  :diminish git-gutter-mode
  :after eyecandy
  :init
  (global-git-gutter-mode) ; Enable git-gutter everywhere
  (git-gutter:linum-setup) ; Make it compatable with linum-mode
  )
```

I am new to Emacs and to use-package so I might be missing something obvious.

**Comment by fice-t** [comment]
The diminish block runs only after `git-gutter-fringe` is loaded. Does it diminish if you do <kbd> M-:</kbd> `(require 'git-gutter-fringe)`?

You could try using separate`use-package` expressions for each package to avoid confusion.

**Comment by braham-snyder** [comment]
I have the same problems with `highlight-indentation-current-column-mode`, `yas-snippet-mode`,  `smartparens-mode`, and `column-enforce-mode`. Not even <kbd>M-x</kbd> `diminish` is working on them for me though, so I think there's a decent chance this isn't `use-package`-related.

**Comment by npostavs** [comment]
> `yas-snippet-mode`

You might have the mode name wrong, I have `:diminish (yas-minor-mode . "Y")` in my init and it's working fine for me.

**Comment by braham-snyder** [comment]
@npostavs Thanks for the heads up--IIUC, <kbd>M-x</kbd> `diminish`'s completion will always show the correct minor mode names for diminishing, as will mousing over the lighter in the mode-line.

Turns out my issue originated in Spacemacs: it already diminishes the above modes (e.g., `column-enforce-mode`) to custom lighters before my `user-config` runs.  Unfortunately, `diminish`--and `:diminish` as well, naturally--doesn't reliably modify a mode's lighter when called a second time on the same mode, at least in Spacemacs. (I'm unsure why, but I think the second call seemed to work for some modes: e.g., `highlight-indentation-mode`.)
