### ISSUE TITLE
Unable to start after byte-compiling with :defer-install

### ISSUE THREAD

**Issue by seagle0128** [jwiegley/use-package#442]
GNU Emacs 25.1, macOS Sierra, lastest use-package

I got this error after adding :defer-install keywords and re-compiling el files.

Example
```elisp
(use-package counsel
  :defer-install t
  :diminish ivy-mode counsel-mode
  :bind (("C-s" . swiper)
         ("C-c u" . swiper-all))
```
Error:
```
Symbol's function definition is void: use-package-install-deferred-package
```

- if I use `(setq use-package-always-ensure nil)` and compile, it works.
- If I delete elc files, and restart, it works.

**Comment by raxod502** [comment]
Ah, this probably slipped by me because I don't byte-compile my init files. Deferred installation will not work if you only load `use-package` at compile-time. The main problem is that, at some point, the deferred installation will have to actually happen, and `use-package` provides the code for it.

I think it might be possible to refactor so that this use case would work, though. We would need to:

1. change the interface for `use-package-ensure-function` so that it returns a form to be evaluated to install the package, instead of actually installing the package
2. put lambdas on the relevant hooks, instead of calls to `use-package-install-deferred-package`.

Alternatively, we could just autoload `use-package-install-deferred-package`, on the assumption that package installation being needed is not the norm. But that might not work, since `use-package-install-deferred-package` is called in a couple of places even when a package does not need to be installed.

Any thoughts?

**Comment by seagle0128** [comment]
Thanks for your reply!
In my opinion, option 1 may work but I am not very sure. Option 2 is not acceptable.
Now I removed all .elc files and disabled to byte-compile my init file. it won't take much more time while starting.

**Comment by raxod502** [comment]
A few comments:

* Why do you say option 2 is not acceptable?
* I don't think you have to disable byte-compilation. You just have to `(require 'use-package)` in your init-file, if you want to use deferred installation. Loading `use-package` will be pretty darn fast, I think (consider all the other features that are loaded by default).
* Regardless of what we do here, it will not affect usage of `use-package` without deferred installation (which will remain the same as before).

**Comment by seagle0128** [comment]
Thanks, @raxod502.
I think option2 is not easy to use for the customers. The word "not acceptable" is not accurate. 
I disable byte-compilation for now, but I will try to use `(require 'use-package)`.

**Comment by raxod502** [comment]
@seagle0128 Why would option 2 be hard to use? It would make everything work transparently, with no changes required in your init-file.

Probably we're talking about different things. What I'm proposing is to put an autoload cookie above `use-package-install-deferred-package` in `use-package.el`, so that if deferred installation needs to happen, then `use-package` is automatically required. (And otherwise, `use-package` remains loaded only at compile-time.)

**Comment by raxod502** [comment]
@jwiegley Can you clarify whether or not packages are intended to be installed during byte-compilation by `:ensure`? It seems like that is the case from my reading of the code, but I'm not sure. Your answer will help establish the appropriate response to this issue (I want to handle deferred installation in a consistent manner with regular installation).

**Comment by npostavs** [comment]
There is some discussion about this in https://github.com/jwiegley/use-package/commit/a591cd244495b9e8dea8b1ebd5eb52a096912b5a

**Comment by jwiegley** [comment]
I don't know. I didn't write that feature, nor do I use it. It would be nice if everything related to `:ensure` moved into a separate package, actually, since I can't really maintain it.

**Comment by jwiegley** [comment]
What was decided for this issue?

**Comment by raxod502** [comment]
It hasn't reached a conclusion. Deferred installation currently does not work with byte-compilation, and fixing this would require rethinking the mechanism by which deferred installation is implemented. I am attempting to address this problem in my package [`with-feature`](https://github.com/raxod502/with-feature), and will therefore most likely not have time to implement the fix in `use-package`. If you feel that this omission is unacceptable, I have no objection to removing support for deferred installation from `use-package` (I'll use a forked version). Otherwise, I'll be happy to provide guidance to anyone who would like to work on the feature.

**Comment by jwiegley** [comment]
@raxod502 I'd prefer to remove :defer-install from core use-package, and to maintain it as a feature in a separate file, `up-deferred.el` or some such, though I'm happy to host that file within the repository alongside `use-package.el`.

**Comment by raxod502** [comment]
@jwiegley Sounds good. Realistically, I will not have time to look at this until winter break. But at that point, I will try to move `:defer-install` to a separate file. This will require some thought, since supporting the functionality will probably require a few additional hooks—it may not be possible to reduce the complexity of `use-package.el` without dropping `:defer-install` support entirely, which was one of the reasons I was considering making a separate package which had such support threaded throughout the design.

**Comment by jwiegley** [comment]
@raxod502 OK, I've removed the keyword and its support code. I rather like how much that simplified some of the logic, since the effect of that keyword appeared in several places. It will be interested to see how we architect this as an add-on, as it will likely require the additional hooks  that you mention. Thanks for all your support, and I hope this work makes it way back into the project!
