### ISSUE TITLE
Continue execution even if a keyword is unrecognized

### ISSUE THREAD

**Issue by joewreschnig** [jwiegley/use-package#483]
If `use-package` encounters an unrecognized keyword it errors, halting execution completely. However, since the keyword list is extensible it may be unknown because the package providing it failed to install, which would otherwise be a recoverable error.

I see three options:
1. As now, stop loading completely.
2. Warn about the unrecognized keyword and its arguments, drop them, and continue loading the package.
3. Warn about the unrecognized keyword and its arguments, do not load the package at all, but otherwise continue execution.

Both 2 and 3 seem preferable to 1 to me, but the choice between them depends on the keyword. For [`:quelpa`](https://github.com/quelpa/quelpa-use-package) I probably want to drop the whole package rather than install it from the wrong place. For [`:minor`](https://github.com/joewreschnig/auto-minor-mode) I probably still want to continue without those particular hooks.

**Comment by nickmccurdy** [comment]
Good points. I feel like 2 would be safer because you don't want an optional or environment specific keyword to cause packages to not load without it being obvious. The warnings should be enough. In the case of 3 you'd definitely need a warning when a package isn't being loaded, but users may be and ignore the error thinking the rest of the `use-package` form is working.
