### ISSUE TITLE
Feature request: give :if higher precedence than :ensure

### ISSUE THREAD

**Issue by oantolin** [jwiegley/use-package#523]
I want to install `csharp-mode` only on my Windows machines, so I'd like:

```elisp
(use-package csharp-mode
  :if (eq window-system 'w32)
  :ensure t
  :defer t)
```

to expand to:

```elisp
(when (eq window-system 'w32)
  (progn
    (use-package-ensure-elpa 'csharp-mode 't 'nil :ensure)))
```

instead of its current expansion:
```elisp
(progn
  (use-package-ensure-elpa 'csharp-mode 't 'nil :ensure)
  (when
      (eq window-system 'w32)))
```

There might be a good reason that currently `:if` has lower priority than `:ensure` that I'm simply unaware of. Is there?

**Comment by jwiegley** [comment]
I've been reluctant to modify this, because it would change semantics in a subtle way that would be very hard to diagnose for those who have come to implicitly rely on the current behavior.

Note that you could customize `use-package-keywords` and just swap the positions of `:if` and `:ensure` on your system.

**Comment by oantolin** [comment]
[Fair enough](https://xkcd.com/1172/), I'll customize `use-package-keywords` then. (I didn't know about that variable --if I did I probably wouldn't have opened the issue.)
