### ISSUE TITLE
New problem with diminish

### ISSUE THREAD

**Issue by DamienCassou** [jwiegley/use-package#574]
When doing a change in my init.el, Emacs sometimes decides to freeze for a few seconds and display that in the `*Messages*` buffer:

```
Saving file /home/cassou/.emacs.d/init.el...
Wrote /home/cassou/.emacs.d/init.el
ad-handle-definition: ‘enable-theme’ got redefined
Configuring package frame...done (0.468s)
ad-handle-definition: ‘pop-to-mark-command’ got redefined
[...]
Wrote /home/cassou/.emacs.d/init.elc
Wrote /home/cassou/.emacs.d/init.{el,elc}
```

This has been like that for quite some time. But with a recent use-package version from git, after Emacs has frozen for a few seconds, I now get all minor modes in the modeline. I usually have them disappear with `:diminish`.

Standard mode-line:
![image](https://user-images.githubusercontent.com/217543/33718516-eaad1ad0-db5d-11e7-8b39-3442bf19fc49.png)

After saving my init.el:
![image](https://user-images.githubusercontent.com/217543/33718484-cbe30470-db5d-11e7-8d60-ca82e640aaed.png)

**Comment by nickmccurdy** [comment]
Which commit are you on? This seems like it's likely an issue in `use-package` but as a workaround I'd recommend trying `delight` instead, it tends to be more stable than `diminish` in my experience.

**Comment by jwiegley** [comment]
@DamienCassou I take it you're using something like `auto-compile` to recompile your `init.el` file?

**Comment by DamienCassou** [comment]
I [am using auto-compile](https://github.com/DamienCassou/emacs.d/blob/master/init.el#L174), indeed:

```
(use-package auto-compile
  :demand t
  :init
  (progn
    (setq auto-compile-display-buffer nil)
    (setq auto-compile-mode-line-counter t)
    (setq auto-compile-source-recreate-deletes-dest t)
    (setq auto-compile-toggle-deletes-nonlib-dest t)
    (setq auto-compile-update-autoloads t))
  :hook (auto-compile-inhibit-compile . auto-compile-inhibit-compile-detached-git-head)
  :config
  (progn
    (auto-compile-on-load-mode)
    (auto-compile-on-save-mode)))
```

I'm following recommendation from [borg](https://github.com/emacscollective/borg) IIRC.

**Comment by jwiegley** [comment]
I don't know what the interaction between these two might be, especially since you're byte-compiling your init file itself. Do you think this is something to be addressed in use-package?

**Comment by DamienCassou** [comment]
I've just seen that [auto-compile](https://github.com/emacscollective/auto-compile) explicitly recommends not byte-compiling the init.el file. I will follow this advice from now on. I'm not sure what use-package could do about it but I was surprised that each compilation of my init file would execute my use-package recipes (as opposed to just expanding and compiling the expansion).

**Comment by npostavs** [comment]
> I was surprised that each compilation of my init file would execute my use-package recipes

Some discussion around that in #285 and https://github.com/jwiegley/use-package/commit/a591cd244495b9e8dea8b1ebd5eb52a096912b5a

**Comment by jwiegley** [comment]
@DamienCassou So, this will be another chapter for the manual, but:

Byte-compiling so that it produces *meaningful* errors and warnings is a tricky then. If you byte-compile and see thousands of warnings about things not being defined, you won't see the ones that are *really* not defined after the package has loaded.

What `use-package` does to counter this is that, **only when byte-compiling**, it injects some `eval-and-compile` forms that attempt to load your package, no matter what your keyword settings are. This is done to bring all of that package's definitions into scope, for the scope of expanding later macro definitions in the init file, and so that we can really see which references are undefined.

Thus, byte-compiling init.el within a running Emacs will cause everything to be loaded again, but this time without doing it the way you've requested. This means that use-package-based init files should only ever be byte-compiled offline, using `emacs --batch -f batch-byte-compile-file`. There's an example of how I do this here:

https://github.com/jwiegley/dot-emacs/blob/master/Makefile#L65

**Comment by DamienCassou** [comment]
Thank you very much for the explanation. It makes sense.
