### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by arunisaac** [jwiegley/use-package#602]
Can we have a new release? I use my distribution's (GNU Guix SD) use-package package, and Guix prefers to package only release tarballs.

Thanks for developing and maintaining this great package!

**Comment by nickmccurdy** [comment]
I assume you mean just a git tag right? If so this would also affect MELPA Stable users.

@jwiegley Do you consider the recent changes stable yet or do you want to wait until they mature some more?

**Comment by arunisaac** [comment]
> I assume you mean just a git tag right?
Yes.

> @jwiegley Do you consider the recent changes stable yet or do you want to wait until they mature some more?
Not a hurry for me. So, do take your time if you need to.

**Comment by jwiegley** [comment]
It's looking fairly good, although the Texinfo manual needs more work. Any volunteers there would be appreciated, since I'd prefer not to release it in its current form.

**Comment by kaushalmodi** [comment]
> although the Texinfo manual needs more work

About the Texinfo manual, sort of related: Org development (`master`) branch now has an [updated Org manual **in** Org][1], which is planned to be used as the primary source for exporting to Texinfo. That means that the `ox-texinfo` that ships with Org has been improved a lot so that just the Org source can be relied on for Texinfo. This might be of interest (switching to Org master branch) for folks who want to contribute to the manual.

[1]: http://lists.gnu.org/r/emacs-orgmode/2017-12/msg00337.html

**Comment by jwiegley** [comment]
I should of course mention that I don't actually use Texinfo here, I just generate it from the Org file.

**Comment by phst** [comment]
Hi, any news about tagging a new release?

**Comment by jwiegley** [comment]
@phst Having just recently merged a potentially disruptive change, let's cut the new release at the beginning of July, to give it a chance to settle down.

**Comment by phst** [comment]
Sounds good, thanks.

**Comment by skuro** [comment]
I guess that's now fixed by [v2.4](https://github.com/jwiegley/use-package/releases/tag/2.4)?

**Comment by arunisaac** [comment]
Yes, this issue is fixed. Thank you!
