### ISSUE TITLE
defvar list variable for :hook modes should work as assummed

### ISSUE THREAD

**Issue by waymondo** [jwiegley/use-package#612]
This is an assumption, but now that `use-package` is getting nice and smart and clean, I'd expect:

```
(defvar writing-modes
  '(org-mode markdown-mode fountain-mode git-commit-mode))
```

Then later on:
```
(use-package face-remap
  :ensure nil
  :hook
  (writing-modes . variable-pitch-mode))
```

To properly apply.

**Comment by dieggsy** [comment]
@waymondo in what way does it not work? Have you seen `use-package-hook-name-suffix`?

**Comment by waymondo** [comment]
The following works:

```elisp
(use-package face-remap
  :hook
  ((org-mode markdown-mode fountain-mode git-commit-mode) . variable-pitch-mode))
```

But when a list variable is substituted as in my original post, `variable-pitch-mode` is not added to the mode hooks.

I can look into it if its not a quick adjustment for @jwiegley.

**Comment by dieggsy** [comment]
@waymondo does it have nothing to do with `use-package-hook-name-suffix` then? In your example, `org-mode`, `markdown-mode`, etc. all work because there's a corresponding variable called `org-mode-hook`, `markdown-mode-hook`, etc. So you'd need to either end your `writing-modes` variable with `-hook`, or set `use-package-hook-name-suffix` to nil and specfy `org-mode-hook`, `markdown-mode-hook` explicitly, at which point just `writing-modes` _should_ work... I think.

FWIW I'm not sure modifying any list variable with `add-hook` is "supported behvior" or stylistically correct, I've gotten comments that suggest it's not before.

**Comment by jwiegley** [comment]
This is starting to get a bit too magical, but since this is just Lisp, you can implement this yourself:

``` emacs-lisp
(eval
`(use-package face-remap
  :ensure nil
  :hook
  (,writing-modes . variable-pitch-mode)))
```

**Comment by jwiegley** [comment]
I'd much rather not add yet-another-meaning for what can appear inside inside the hook forms, especially since people are going to want to use variables that may not exist until after the module has loaded. Your use case seems specialized enough that just doing it with plain Lisp feels like the right answer.

**Comment by dieggsy** [comment]
Oh, @waymondo sorry about that, ignore my second reply there. I see the point now, I completely misunderstood what you meant, and the point of your code. The point is just you can't define the list of hooks to use in use-package with a variable. My bad.
