### ISSUE TITLE
setq set by :config is not valid, how can I write it?

### ISSUE THREAD

**Issue by nrikiji** [jwiegley/use-package#621]
It will be a basic question. setq set by config is not valid, how can I write it?

It will be as expected
```
(add-to-list 'auto-mode-alist '("\\.php\\'" . php-mode))
(add-hook 'php-mode-hook
          '(lambda()
             (setq tab-width 4)
             (setq indent-tabs-mode t)
             ))
```

It will not be as expected.
```
(use-package php-mode
  :ensure t
  :mode(("\\.php\\'" . php-mode))
  :config
   (setq tab-width 4)
   (setq indent-tabs-mode t)
 )
```

**Comment by whxvd** [comment]
There is a package named php-mode and a major mode named php-mode. php-mode is provided in php-mode.

`:config` stuff is run after loading the package. Local to every buffer that is brought into a mode, the corresponding mode hook is run.

`tab-width` and `indent-tabs-mode` are buffer-local variables. They "automatically become buffer-local when set" (M-x describe-variable RET tab-width RET).

When the package php-mode is loaded, it may be because a .php file is loaded. But even then the buffer for the .php file probably does not exist, yet. Apart from that a package usually is loaded at most once.

**Comment by whxvd** [comment]
Maybe interesting to look at: `setq-default`.

**Comment by whxvd** [comment]
I (re)edited the (now-)previous comment several times. Now it is final.

**Comment by whxvd** [comment]
`setq-default` behaves like `setq` on variables that are not buffer-local. And - well - it sets the default value for buffer-local ones. So it is safe and probably also sane to use `setq-default` instead of `setq` whenever you globally want to change something that may be (or not, in the future (or past)) buffer-local.

`setq-default` is quite long. I use the following in my init file:
```
(defmacro setd (&rest x)
  "Short for `setq-default'."
  (cons 'setq-default x))
```

**Comment by nrikiji** [comment]
Thank you.
I wanted to do something!!

**Comment by dieggsy** [comment]
@whxvd why not just `(defalias 'setd 'setq-default)`

**Comment by whxvd** [comment]
@dieggsy That's better. Thank you!
