### ISSUE TITLE
imenu support not working

### ISSUE THREAD

**Issue by CSRaghunandan** [jwiegley/use-package#635]
I've the following setting in my init file `(setq use-package-enable-imenu-support t)` and I can confirm that this feature used to work before, but maybe a recent commit broke the imenu support?

Can someone please try to reproduce this?

Thanks

**Comment by nickmccurdy** [comment]
I noticed that recently, it doesn't seem to populate the imenu differently when enabled. I just get whatever I had in Emacs Lisp mode.

**Comment by jwiegley** [comment]
I've never used that command, so I wouldn't be surprised if it broke during the last round of refactoring.

**Comment by waymondo** [comment]
It still works for me. Are you enabling it before `(require 'use-package)`?

**Comment by CSRaghunandan** [comment]
@waymondo  Yes, I am running `(require 'use-package)` before enabling imenu for use-package.

Also, which version of use-package are you running?

**Comment by waymondo** [comment]
@CSRaghunandan I'm on `use-package-20180314.1143` via MEPLA currently.

**Comment by seagle0128** [comment]
Make sure put `(setq use-package-enable-imenu-support t)` before `(require 'use-package)`.

**Comment by CSRaghunandan** [comment]
@seagle0128 That solved the issue 👍 

Closing the issue.

**Comment by lrustand** [comment]
This is still not working.

**Comment by jwiegley** [comment]
@lrustand Can you say more about your setup and the steps you are using to reproduce the failure? Since others have reported it being fixed, I just want to be sure we're comparing the same things. Thank you.

**Comment by lrustand** [comment]
Hmm, it seems it was actually working, only that the default presentation of it in imenu is extremely hard to find. I expected the entries to show up with all the other entries, but they don't. Instead there is one single entry called Packages, which you have to select and press enter to get a list of just the packages entries. This is not documented anywhere, and I would say it is highly unintuitive. It took me many hours of troubleshooting before I randomly noticed the Packages entry in the imenu list.

**Comment by seagle0128** [comment]
Suggest to put `(setq use-package-enable-imenu-support t)` in `early-init.el` to make sure it works.

**Comment by alphapapa** [comment]
> Hmm, it seems it was actually working, only that the default presentation of it in imenu is extremely hard to find. I expected the entries to show up with all the other entries, but they don't. Instead there is one single entry called Packages, which you have to select and press enter to get a list of just the packages entries. This is not documented anywhere, and I would say it is highly unintuitive. It took me many hours of troubleshooting before I randomly noticed the Packages entry in the imenu list.

@lrustand Using a tool like `consult-imenu`, which presents the entries in a flattened manner, will likely help with that.  Imenu's inherent hierarchical structure is less convenient for completion and scanning.

**Comment by gamb** [comment]
As far as I can tell it isn't necessary to set `use-package-enable-imenu-support` after `use-package` is loaded, so long as it gets set via `custom-set-variables` instead of `setq` you can define it any time

**Comment by jonmoore** [comment]
Confirming, since I also spent time on this.
- The imenu support _does_ work if `use-package-enable-imenu-support` is set after `use-package` is loaded, as long as one uses a method like `setopt` that respects `custom-set`.  The comment in the docs for `use-package-enable-imenu-support` that this "[m]ust be set before loading ‘use-package’." is incorrect.   There is no need to futz around with early-init.el, etc.
- The display is unintuitive when calling `imenu`, mainly because of how `lisp-mode` sets `lisp-imenu-generic-expression`.  This puts "function" entries for `defun`, `defmacro`, etc. as leaf entries at top level, and puts variables and types in second-level trees.  `use-package` follows this approach by putting entries for packages under a second-level "Packages"  tree.
- This is exacerbated by `imenu` (1) requiring one to open up sub-trees to view entries in them (2) not prominently separating these sub-trees from the top-level leaf entries
 
`consult-imenu` is more usable than `imenu` here as (1) it shows the imenu hierarchy in a flattened searchable form (2) it indicates the tree structure clearly and allows for two-key navigation to sub-trees, e.g. "p " to visit and narrow to the "Packages" sub-tree.
