### ISSUE TITLE
Is there support for subpackages?

### ISSUE THREAD

**Issue by Wagk** [jwiegley/use-package#659]
Hello,

I would like to be able to spin off configuration of large packages into smaller `use-package` statements. One good example would be `org-mode`

I would like to be able to do the following. `org-capture` is large enough that I would like to define separate trigger keybindings as well as to mess around with its keymaps and perform some additional configuration. 
```
(use-package org)

(use-package org-capture
  :after (org))
```

However in the above block `use-package` complains that it cannot find `org-capture` in any of the package repositories it looked through, and fails.

I'd like some advice on whether this is an already solved problem and if there's some other direction I can pursue regarding organising my package configuration.

**Comment by dieggsy** [comment]
@Wagk do you have `use-package-always-ensure` set to `t`? If so, you may want to include `:ensure nil` in the `org-capture` declaration, because indeed it's not in the package repositories.

This should work though, as `use-package` should work with any `feature` (loosely, if it has a `(provide 'feature-name)` at the bottom of the file)

**Comment by Wagk** [comment]
I actually do have `use-package-always-ensure` set to `t`.

Setting `:ensure nil` did work. Cheers!
