### ISSUE TITLE
The hook syntax is a bit weird. I think

### ISSUE THREAD

**Issue by alienbogart** [jwiegley/use-package#695]
In this example from the manual it is very clear what is going on: `(add-hook 'text-mode-hook 'auto-fill-mode)`: the text-mode-hook will run auto-fill-mode whenever its conditions are true. Use package does it different:

```
(use-package ace-jump-mode
  :hook prog-mode)
```

If I understand it correctly, `prog-mode-hook` runs when `ace-jump-mode` is true. I see no reason to invert the syntax, but whatever, that's understandable. But what heck is going on here?

```
(use-package ace-jump-mode
  :commands ace-jump-mode
  :init
  (add-hook 'prog-mode-hook #'ace-jump-mode)
  (add-hook 'text-mode-hook #'ace-jump-mode))
```

Why `ace-jump-mode` repeated four times? What's with the "#"? What is the difference in functionality between those repetitions? The syntax should be simpler and more obvious. or the documentation should be better and more extensive.

**Comment by waymondo** [comment]
In the example:

```
(use-package ace-jump-mode
  :hook prog-mode)
```

The way you can read it is "hook `ace-jump-mode` into `prog-mode`" which translates into the plain emacs manual way you described.

> If I understand it correctly, prog-mode-hook runs when ace-jump-mode is true

This isn't the case. It is simply calling `(ace-jump-mode)` within `prog-mode-hook`, which runs whenever `(prog-mode)` is called, which happens when you open a file in most programming modes.

In your last example, it is illustrating the autoloading mechanic of the `:commands` keyword. I think the README does a good job explaining why `ace-jump-mode` is included in this scenario:

> When you use the :commands keyword, it creates autoloads for those commands and defers loading of the module until they are used. Since the :init form is always run -- even if ace-jump-mode might not be on your system -- remember to restrict :init code to only what would succeed either way.

If the `:init` keyword was instead `:config`, the `:commands` keyword wouldn't be necessary because `:config` is only run after the package is loaded.

Finally, `#'` is a version of quoting that enables bye compilation. Its optional but suggested by many. Here's a good article about that: http://endlessparentheses.com/get-in-the-habit-of-using-sharp-quote.html

**Comment by mrbig033** [comment]
Okay. I'll study this with more detail, and maybe create a pull request to make it clear for people like me? If you think it would be a good idea.

**Comment by dieggsy** [comment]
@mrbig033 I'd say give it some time, this may be a case of getting used to how emacs operates.

**Comment by mrbig033** [comment]
I'm sure of it, I was just thinking of making it more clear (noob proof) in the documentation.

**Comment by skangas** [comment]
I don't think see anything actionable here, and I agree with the assessment that this probably just takes some getting used to. Closing.
