### ISSUE TITLE
dependencies between packages

### ISSUE THREAD

**Issue by edvorg** [jwiegley/use-package#70]
there is no way, to set runtime dependencies for a package. what do you think about adding :requires LIST to the use-package function? It must guarantee loading required package before loading requiring package.

**Comment by lionel-** [comment]
What if the DAG was specified separately before loading the packages, so that there would be no performance cost for those that don't use this feature? It could look like:

```lisp
(use-package-deps
 :evil (evil-leader evil-matchit)
 :key-chord (ess-site pandoc-mode)
)
```

**Comment by lionel-** [comment]
The situation now is a bit constraining for the user as we have to manually maintain a sorted graph in our init file. This is additional work and this can go against other organising principles.

For example I like to have important major-mode packages at the top, then a section with packages to organise projects, then a section related to code editing, etc. But I can't always respect this hierarchy because of the dependencies between packages.

**Comment by MaikuMori** [comment]
Maybe this helps, haven't used myself, but looks interesting. It's a
wrapper around use-package.

https://github.com/edvorg/req-package
