### ISSUE TITLE
Check if package is installed

### ISSUE THREAD

**Issue by holocronweaver** [jwiegley/use-package#717]
Does `use-package` provide a package backend agnostic way to check if a package is installed?

For example, while `package` is  a popular backend, I use `straight.el` with `use-package`. If I want to write a config that is independent of `use-package` backend, how can I check whether packages are installed?

Or is doing such a check before installing performance-wise unnecessary with `use-package`?

For example, with `package` I used to do:

```
(unless (package-installed-p package)
  (package-install package)))
```

As a related followup, is there a backend agnostic way to get a list of installed packages?

**Comment by slippycheeze** [comment]
I'm not the upstream, but I can answer your question: `use-package` implements the specific logic you described there in the default, package.el based `use-package-ensure-elpa`: [use-package-ensure.el line 155](https://github.com/jwiegley/use-package/blob/master/use-package-ensure.el#L155)

The logic, sensibly, is entirely within that function, so that when, eg, `straight.el` overrides it with their own implementation (and thus takes over the `:ensure` keyword entirely), it has to implement the same check.

Which, of course, would have packages installed, but also, `package-installed-p` returning `nil` as there was no corresponding ELPA package present on the system.  

There is no broader abstraction over package systems present.

**Comment by holocronweaver** [comment]
I think the key takeaway is that calling `use-package` multiple times on the same package probably won't have much if any performance impact. While it would be nice to have `use-package` provide more convenience wrappers which backends can override, I don't think it's necessary in my use case.
