### ISSUE TITLE
Putting configuration inside :config vs outside

### ISSUE THREAD

**Issue by bradrn** [jwiegley/use-package#723]
How does the behaviour of the following two `use-package` declarations differ? Which is recommended?
```elisp
;; option 1
(use-package some-package
  :config
  (some-configuration))

;; option 2
(use-package some-package)
(some-configuration)
```

**Comment by a13** [comment]
I think the first one is better since you can see, to which package you configurations belong to. 

besides that, you can't do the same for other keywords, is there any reason to break the consistency?

**Comment by dieggsy** [comment]
@bradrn In option 1, `(some-configuration)` is only executed when and if the package loads. In option 2, it is executed unconditionally. If you don't do any deferred loading, they're effectively the same (but the first seems cleaner stylistically as @a13  pointed out), but if you do, the first is preferable since `(some-configuration)` may reference vars/functions that have not yet been loaded.

**Comment by bradrn** [comment]
Thanks @dieggsy! But I'm still slightly confused about a part of this problem: you've explained very clearly what happens when you add deferred loading (would that be `:defer t`?) vs nothing, but from experiments I've also found that `:ensure t` also changes the behaviour of those two cases: with `:ensure t`, both cases work as expected, but without `:ensure t`, the second case fails if the package isn't already installed. Why is this?

**Comment by bradrn** [comment]
After reading a few other issues on here and inspecting the output of `pp-macroexpand-last-sexp`, I think that I've managed to answer my own question. My issue was that I didn't realise that `use-package` would only install an uninstalled package if `:ensure t` was used.
