### ISSUE TITLE
Q: how can I support alternative bindings for the same key?

### ISSUE THREAD

**Issue by stsquad** [jwiegley/use-package#761]
Say I want to use a new feature which isn't available on all my Emacs' instances but re-use the keybinding. How can I achieve this? I tried:

    (use-package swiper
      :commands (swiper swiper-isearch)
      :init (defalias my-swiper-fn
                  (if (fboundp 'swiper-isearch) 'swiper-isearch 'swiper))
      :ensure t
      :bind ("C-s" . my-swiper-fn))
      
but that gets confused and sets up my-swiper-fn as an autoload. Do I just need to have a trampoline function?

    (defun my-swiper-fn (&optional INITIAL-INPUT)
      "Wrapper around swiper/swiper-isearch."
      (interactive)
      (if (fboundp 'swiper-isearch)
          (call-interactively #'swiper-isearch)
        (call-interactively #'swiper)))

    (use-package swiper
      :ensure t
      :bind ("C-s" . my-swiper-fn))

I worry that there may be undesirable interactions this way.

**Comment by raxod502** [comment]
What about this?

```elisp
(when (fboundp 'swiper-isearch)
  (bind-key "C-s" #'swiper-isearch))
```

There's no need to use `:bind` for _all_ your keybindings.

**Comment by stsquad** [comment]
@raxod502 is the :config section? Will that always be applied after :bind options?

**Comment by thomasf** [comment]
:config is  run after the package is loaded.

If you want to understand the order of execution in a use-package instance I suggest that you install the macrostep package because it is a convenient way to inspect result of elisp macros.

![image](https://user-images.githubusercontent.com/330847/56345091-39ed1f80-61bf-11e9-87c0-f9d743ea6fd1.png)

expands into

![image](https://user-images.githubusercontent.com/330847/56345108-41acc400-61bf-11e9-9ea4-52b8a1bf0c22.png)

**Comment by stsquad** [comment]
Hmm I have been indeed using macrostep-expand but for some reason I don't yet understand the second (bind-key) form suggested by @raxod502 doesn't override the fallback :bind case.

**Comment by raxod502** [comment]
It does seem that `:bind` is executed _after_ `:init`. That seems undesirable to me, since the user might want to override some `:bind` configuration in `:init`, while on the other hand I can't think of any reason why keybindings would need to be established _after_ `:init` code. Any thoughts on why this is the case @jwiegley?

@stsquad The simpler solution for you would be

```elisp
(use-package swiper
  :init

  (if (fboundp 'swiper-isearch)
      (bind-key "C-s" #'swiper-isearch)
    (bind-key "C-s" #'swiper)))
```

**Comment by skangas** [comment]
> It does seem that `:bind` is executed _after_ `:init`. That seems undesirable to me, since the user might want to override some `:bind` configuration in `:init`, while on the other hand I can't think of any reason why keybindings would need to be established _after_ `:init` code. Any thoughts on why this is the case @jwiegley?

There is `:preface` too, which is evaluated before `:bind`.

As for the rest, I believe @raxod502 has answered the question in https://github.com/jwiegley/use-package/issues/761#issuecomment-484312684. I'm therefore closing this issue. Please report back if there is anything here that is still unresolved, and we can reopen. Thanks.
