### ISSUE TITLE
:chords local keymap doesn't work?

### ISSUE THREAD

**Issue by indigoviolet** [jwiegley/use-package#777]
```
(use-package org
  ....

  ;; Uncommenting this leads to an error (void-variable org-mode-map)
  ;; :chords
  ;; (:map org-mode-map
  ;;       ("oo" . hydra-org-template/body))

   ;; This works
  :bind
  (:map org-mode-map
        ("C-<" . hydra-org-template/body))
        )
```
I'm having a bit of trouble binding a chord to a local keymap - I'm probably doing something wrong, help would be appreciated. I'm using straight.el if that's relevant, and I'm able to use `:chords`  for global key chords without any problems.

**Comment by waymondo** [comment]
This is happening because the `use-package` form is evaluated before org is loaded and `org-mode-map` has not be autoloaded and the `:chords` keyword is not accounting for that. The simple fix here is to move the chord binding into the `:config` keyword handling:

```
(use-package org
  :config
  (bind-chord "oo" #'hydra-org-template/body org-mode-map))
```

You could also use the `:chords` keyword as you have it if you add `:demand t`, but that would cause `org` to be loaded when the `use-package` form is evaluated.

**Comment by indigoviolet** [comment]
Thanks for the quick explanation! I will use the approach you described. It was a bit confusing that `bind` supports this behavior but `chords` doesn't.

**Comment by waymondo** [comment]
Yeah I agree. I will work on a PR to address that in the near future.
