### ISSUE TITLE
Add a way to specify keymap in :bind keyword for `use-package`

### ISSUE THREAD

**Issue by Fuco1** [jwiegley/use-package#88]
For example, I call `use-package preview` from inside `use-package latex` (which still is called from inside `use-package tex-site`). I'd like to setup some bindings for preview, but they shouldn't go to global map, but latex map.  Right now, I have to specify `:commands` and then bind the keys in `:init` section.

I'd implement this myself but I'm unsure how to handle it "properly". Should I add new keyword, or assume that e.g. first symbol in `:bind` is name of a map? I'm not sure if you follow any conventions like that.

**Comment by ThibautVerron** [comment]
It seems to me that this is not a corner case at all: any package defining a major mode is supposed to define a mode map, and keys should be bound in that map instead of the global map. Using `:config (progn (bind-key ...` for all major modes seems like an unnecessary annoyance. 

To add yet another suggestion in the balance, how about adding a `:map keymap` keyword to tell `use-package` that the current package binds keys in `keymap` instead of the global map (which would be the default)?

**Comment by Fuco1** [comment]
I've just realized that it could just take the form and put `bind-keys` in front of it. That way it would use the same syntax and be "compatible" with the `bind-keys` call in `:config` section.

**Comment by sindikat** [comment]
What's the current status of this feature? Because I have lots of keymap-specific keybindings for many packages, I went with [this solution](http://emacs.stackexchange.com/a/12594/3972). IOW, I use `with-eval-after-load` to ensure that the binding is put into the map only after it's loaded, which can be any time.

**Comment by vermiculus** [comment]
@sindikat why not put that form in a `:config` key, then?

Though I would like to see some new discussion on this :smile:

**Comment by jwiegley** [comment]
This is solved by #129.
