### ISSUE TITLE
Dead MELPA link

### ISSUE THREAD

**Issue by mcandre** [jwiegley/use-package#950]
The new MELPA homepage has moved to https://melpa.org/#/

**Comment by derekpappas** [comment]
The use-package link is https://melpa.org/#/use-package

**Comment by nopdotcom** [comment]
I think this can be closed; it doesn’t appear to apply to the current codebase.

@mcandre: The homepage is obviously `https://melpa.org/`, with no `#/`. Nobody *ever* types the empty search fragment, except maybe the people who wrote the too-clever JavaScript.

@derekpappas: It’s a shame that MELPA ignores REST, both in URL structure and in implementation.

```bash
$ curl -s 'https://melpa.org/#/use-package' | egrep '<(h1|title)>'
  <title>MELPA</title>
      <h1><span class="archive-name">MELPA</span> (Milkypostman’s Emacs Lisp Package Archive)</h1>
```

If details were linked under `https://melpa.org/package/use-package` or `/p/use-package` or `/~use-package`, something useful could be done with that URL.

Incidentally, MELPA scores an own goal here. On the “Getting Started” page, the second paragraph links to an *actual fragment*, but of course MELPA’s JavaScript navigation has been hijacked, and goes somewhere random instead of the intended destination.

![melpa-org-search-fragment](https://user-images.githubusercontent.com/1357866/188528225-ba6090e0-7a66-4228-8b00-10420ab200cb.png)

**Comment by skangas** [comment]
It seems like the links have been updated, so I'm closing this now. Please reopen or report a new issue if you spot any other dead links.
