### ISSUE TITLE
:bind* not working anymore?

### ISSUE THREAD

**Issue by Trisk3lion** [jwiegley/use-package#991]
Hello, thanks for a great package!

":bind*" stopped working for me after updating to the last version of bind-key. So something in the latest commits probably did it.

I haven't looked into it more then that yet thou..

**Comment by cxa** [comment]
Downgrade package `bind-key` or wait for new update.

(P.S. the simple way is copy source from `Download` button on <https://stable.melpa.org/#/bind-key>, override `~/.emacs.d/elpa/bind-key-20220807.1553/bind-key.el`，and delete `bind-key.elc` in that dir.

**Comment by pegzmasta** [comment]
I hope they update it soon.  I have a lot of ":bind*" tags in my startup file, and they no longer work.

**Comment by realcomplex** [comment]
For what it's worth, I submitted a one-line pull-request (#993) which fixes the issue. You could try to use my fork for now or just apply the fix yourself. Or really, the problem is that `override-global-mode` isn't turned on automatically anymore like before, so turning that minor mode on manually in your config should also do the trick.

**Comment by jwiegley** [comment]
I just noticed this as well, pulling in the fix now.

**Comment by jwiegley** [comment]
Thank you for addressing this so quickly @realcomplex.
